### ISSUE TITLE
关于论文中的几个问题

### ISSUE THREAD

**Issue by XiaoJiNu** [qintonguav/ParkingE2E#1]
你好
     关于论文中有几个疑问想请教一下。
     1. 如何实现车位选择？没有看到车位检测结果
     2. 预测多条轨迹，选择哪个轨迹？
     3. 如果给定轨迹负样本，应该怎样学习？loss如何设计？
     4. 预测的轨迹是二维(x,y)坐标，如果路面不平或者针对机械库位，此时预测的轨迹没有高度z值，最终停车是否就不会准确了？是否应该考虑将轨迹标注为三维坐标？

**Comment by ChauncyLeee** [comment]
@XiaoJiNu 感谢您的关注。
1.  关于车位选择，训练过程中使用专家轨迹末端点并添加扰动；在实车推理过程中，通过人机交互选取IPM图中目标车位点。
2. 我们没有同时预测多条轨迹的操作，关于多条轨迹的选择，可以参考VADv2论文，该论文将回归问题转化为分类问题，选择概率最大的轨迹。
3. 给定轨迹负样本，可以考虑采用对比学习来构建损失。
4. 您的担忧是有道理的，对于一些地面凹凸不平的复杂场景，应该考虑到高度的影响，从而获得更准确的结果。
