### ISSUE TITLE
bev_encoder.py代码下72行，有点问题？

### ISSUE THREAD

**Issue by longjianquan** [qintonguav/ParkingE2E#4]
img_feature = tgt_feature + self.pos_embed，img_feature   unused

**Comment by 370332847** [comment]
According to the explanation of the third picture in the paper, "_The architecture of the target query illustrates that **we add the same positional encoding to the target feature and camera feature** to establish ..._", I think the correct code should be
`img_feature = img_feature + self.pos_embed`

**Comment by nimda-z** [comment]
我对比测试了:
(1)img_feature = tgt_feature + self.pos_embed; 
(2)img_feature = img_feature + self.pos_embed;
它们推理的结果是差不多的，这个让给我很疑惑。
下面是1708689773_right这条数据的第1帧和第101帧数据的推理结果（图中左测是(1)的结果，右测是(2)的结果，蓝色的轨迹线是训练集，绿色的轨迹线是推理结果解析出来的，红色点为泊车终点）。
![20240920-113925](https://github.com/user-attachments/assets/ee17f369-d585-4d34-8ee8-7ce97ea22fdf)
![20240920-113935](https://github.com/user-attachments/assets/6dfbf80a-3079-4395-9a73-e0b9adf8eb28)

**Comment by ChauncyLeee** [comment]
@longjianquan @370332847 @nimda-z Thank you for your interest in this project! We will review the issues you mentioned, and if there are indeed any inconsistencies, we will make the necessary corrections.

**Comment by ChauncyLeee** [comment]
@nimda-z 后续我们会更新训练模型

**Comment by ChauncyLeee** [comment]
We've fixed the corresponding code and provided a new network model.
