### ISSUE TITLE
pretrained model & test data error

### ISSUE THREAD

**Issue by lihu2022** [qintonguav/ParkingE2E#6]
halo!!  I am soory that you provided a  link including pretrained model and test data in readme.md, but both of them can not be downloaded.

**Comment by lihu2022** [comment]
please provide other methods to get the data and pretrained model

**Comment by hz-ants** [comment]
通过百度网盘分享的文件：ParkinE2E-DATA
链接：https://pan.baidu.com/s/1avcdVcdoHHj0UbEo04PtGA?pwd=cisc 
提取码：cisc

**Comment by lihu2022** [comment]
Thank you very much!!!,although   i have downloaded 2 days ago !!
